# Generated by Django 2.0.5 on 2018-05-21 18:15

from django.db import migrations, models
import games.utils


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180521_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')], default=games.utils.Genero('M'), max_length=2),
        ),
    ]
